
namespace ChessCompStompWithHacksLibrary
{
	using DTLibrary;

	public class Credits_Font
	{
		public static void Render(IDisplayOutput<ChessImage, ChessFont> displayOutput, int width, int height)
		{
			string text = "The font used in this game was generated by metaflop." + "\n"
				+ "https://www.metaflop.com/modulator" + "\n"
				+ "\n"
				+ "The font is licensed under SIL Open Font License v1.1";

			displayOutput.DrawText(
				x: 10,
				y: height - 10,
				text: text,
				font: ChessFont.Fetamont20Pt,
				color: DTColor.Black());
		}
	}
}
